apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: mercury
  labels:
    name: mercury
    app: musicgang
    kind: Kustomization
namespace: mercury
resources:
  - ../../../base
  - mercury.yaml
patches:
  - musicgang-api-deploy.yaml
