apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mercury
resources:
  - ../../../base
  - mercury.yaml
images:
  - name: iacopomelani/music-gang-api
    newTag: mercury
  - name: redis
    newTag: 6.2.6
  - name: postgres
    newTag: 9.6.24
