apiVersion: v1
kind: Namespace
metadata:
  name: mercury
  labels:
    name: mercury
    app: musicgang-dev-mercury
    kind: namespace
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: mercury
  labels:
    name: nginx-ingress
    app: musicgang-dev-mercury
    kind: ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: mercury.musicgang.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: musicgang-api-service
                port:
                  number: 8888
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mercury-postgres-pv
  labels:
    name: mercury-postgres-pv
    app: musicgang-dev-mercury
    kind: pv
spec:
  capacity:
    storage: 300Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: do-block-storage
  hostPath:
    path: /var/kube-pv/dev/mercury/mercury-postgres-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mercury-redis-pv
  labels:
    name: mercury-redis-pv
    app: musicgang-dev-mercury
    kind: pv
spec:
  capacity:
    storage: 35Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: do-block-storage
  hostPath:
    path: /var/kube-pv/dev/mercury/mercury-redis-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: mercury
  labels:
    name: postgres-pvc
    app: musicgang-dev-mercury
    kind: pvc
spec:
  selector:
    matchLabels:
      app: musicgang-dev-mercury
  storageClassName: do-block-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: mercury
  labels:
    name: redis-pvc
    app: musicgang-dev-mercury
    kind: pvc
spec:
  selector:
    matchLabels:
      app: musicgang-dev-mercury
  storageClassName: do-block-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 35Mi
