apiVersion: apps/v1
kind: Deployment
metadata:
  name: musicgang-api-deploy
  labels:
    name: musicgang-api-deploy
    app: musicgang
    kind: deploy
spec:
  selector:
    matchLabels:
      name: musicgang-api-pod
      app: musicgang
      kind: pod
  template:
    metadata:
      labels:
        name: musicgang-api-pod
        app: musicgang
        kind: pod
    spec:
      containers:
        - name: musicgang-api
          image: iacopomelani/music-gang-api:mercury
