apiVersion: v1
kind: Service
metadata:
  name: musicgang-api-service
  labels:
    name: musicgang-api-service
    app: musicgang
    kind: cluster-ip
spec:
  selector:
    name: musicgang-api-pod
    app: musicgang
    kind: pod
  type: ClusterIP
  ports:
    - port: 8888
      targetPort: 8888
