apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: musicgang-stage
resources:
- stage.yaml
- ../../base
replicas:
- count: 1
  name: musicgang-api-deploy
images:
- name: iacopomelani/music-gang-api
  newTag: v0.0.5rc2
- name: redis
  newTag: 6.2.6
