apiVersion: v1
kind: Namespace
metadata:
  name: musicgang-stage
  labels:
    name: musicgang-stage
    app: musicgang
    kind: namespace
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: musicgang-stage
  labels:
    name: nginx-ingress
    app: musicgang
    kind: ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: stage.musicgang.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: musicgang-api-service
                port:
                  number: 8888
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: stage-postgres-pv
  labels:
    name: stage-postgres-pv
    app: musicgang
    kind: pv
spec:
  capacity:
    storage: 300Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: do-block-storage
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /var/kube-pv/stage/postgres-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: stage-redis-pv
  labels:
    name: stage-redis-pv
    app: musicgang
    kind: pv
spec:
  capacity:
    storage: 30Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: do-block-storage
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /var/kube-pv/stage/redis-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: musicgang-stage
  labels:
    name: postgres-pvc
    app: musicgang
    kind: pvc
spec:
  storageClassName: do-block-storage
  selector:
    matchLabels:
      app: musicgang
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: musicgang-stage
  labels:
    name: redis-pvc
    app: musicgang
    kind: pvc
spec:
  storageClassName: do-block-storage
  selector:
    matchLabels:
      app: musicgang
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Mi
