apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deploy
  labels:
    name: postgres-deploy
    app: musicgang
    kind: deploy
spec:
  selector:
    matchLabels:
      name: postgres-pod
      app: musicgang
      kind: pod
  template:
    metadata:
      labels:
        name: postgres-pod
        app: musicgang
        kind: pod
    spec:
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
      containers:
        - name: postgres
          image: postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: admin
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_DB
              value: music-gang-api
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
