apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deploy
  labels:
    name: redis-deploy
    app: musicgang
    kind: deploy
spec:
  selector:
    matchLabels:
      name: redis-pod
      app: musicgang
      kind: pod
  template:
    metadata:
      labels:
        name: redis-pod
        app: musicgang
        kind: pod
    spec:
      volumes:
        - name: redis-storage
          persistentVolumeClaim:
            claimName: redis-pvc
      containers:
        - name: redis
          image: redis
          env:
            - name: ALLOW_EMPTY_PASSWORD
              value: "yes"
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-storage
              mountPath: /var/lib/redis/data
